# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

##### DOT FILES
source ~/.env

##### BINDINGS
bindkey "^R" history-incremental-search-backward
bindkey "\e[A" history-beginning-search-backward
bindkey "\e[B" history-beginning-search-forward

##### PERSONAL ALIASES
alias ll="ls -l"
alias python="/usr/local/bin/python3"
alias pip="pip3"
alias i2prouter="/Applications/i2p/i2prouter"

##### GITHUB ALIASES
source ~/.github_aliases

##### EXPORT PATH
export PATH="$PATH:$HOME/kafka_2.13-2.8.0/bin"

##### SPECIFIC ALIASES
source ~/.aliases

##### ZSH
fpath+=$HOME/.zsh/pure

##### DIRECTORIES
alias ghd="cd $HOME/Documents/development/github"
alias gld="cd $HOME/Documents/development/gitlab"

##### EXECUTABLES
source ~/.executables

source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source $HOME/Documents/development/github/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
